language: java
sudo: true
dist: trusty
before_install:
  - chmod +x mvnw
  - chmod +x idea-plugin/gradlew
cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
install: true
matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk11
    - jdk: openjdk15
    - jdk: openjdk-ea
  allow_failures:
    - jdk: openjdk-ea
script:
  - "cd ./p3c-pmd"
#  - "../mvnw clean install site -U -e -X -Dmaven.javadoc.skip=false"
  - "travis_wait ../mvnw clean install site -U -e -Dmaven.javadoc.skip=false"
  - "cd ../"
  - "cd ./idea-plugin"
  - "cd ./p3c-common"
  - "travis_wait ../gradlew publishToMavenLocal --scan -s"
  - "cd ../"
  - "cd ./p3c-idea"
  - "travis_wait ../gradlew publishToMavenLocal --scan -s"
  - "cd ../"
  - "travis_wait ./gradlew buildPlugin --scan -s"